### ISSUE TITLE
Stuck on "Initializing Airsim"

### ISSUE THREAD

**Issue by Tzoulio** [microsoft/PromptCraft-Robotics#21]
After running the simulation environment and chatgpt_airsim.py the terminal is stuck on "Initializing AirSim...". It used to work normally until a couple of days ago. Any ideas what could be the issue? 
![image](https://github.com/microsoft/PromptCraft-Robotics/assets/86010455/ec71a379-1caf-4b49-ae54-7af9e6d2078c)

**Comment by langxinspieder** [comment]
I have met the same question！Do you deal with it？

**Comment by Tzoulio** [comment]
> I have met the same question！Do you deal with it？

Restarting my computer solved the issue for me.
